version: "3.3"
services:
  database:
    container_name: postgres_hakooh
    image: postgres:latest
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hakooh_admin
      - POSTGRES_DB=hakooh_db
    ports:
      - 5432:5432
