# Generated by Django 4.2.2 on 2023-06-23 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('birth', models.DateField()),
                ('user_key', models.IntegerField()),
                ('validated_birth', models.BooleanField()),
            ],
        ),
    ]
