# Generated by Django 4.2.2 on 2023-06-23 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.CharField()),
                ('postal_code', models.IntegerField()),
                ('number', models.IntegerField()),
                ('complement', models.TextField()),
                ('country', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
            ],
        ),
    ]
